name: Check Update
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: "x64"

      - name: get version
        run: |
          python --version;
          pip --version;

      - name: install deps
        working-directory: ./scraper
        run: |
          ls;
          pip install -r requirements.txt;

      - name: run check
        working-directory: ./scraper
        run: |
          python ./check.py;
