name: Check Update
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7" # Version range or exact version of a Python version to use, using semvers version range syntax.
          architecture: "x64" # (x64 or x86)
      - run: |
          python --version;
          pip --version;
          cd scraper;
          ls;
          pip install -r requirements.txt;
          python ./check.py;
